name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      # TODO: Change to production branch
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'bun.lock'
      - 'package.json'
      - 'prisma/**'
      - 'src/**'
      - 'tsconfig.json'
      - 'vite.config.ts'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 📥 Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.16

      - name: 📥 Download deps
        run: bun install

      - name: Build application for Cloudflare Workers
        run: bun run build
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            DATABASE_URL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
